name: Verify RPM

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  verify-rpm:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install necessary tools
      - name: Install RPM tools
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm

      # Step 3: Verify the RPM file exists
      - name: Verify RPM file exists
        run: |
          if [[ ! -f devops-gpt-0.0.1.x86_64.rpm ]]; then
            echo "RPM file not found!"
            exit 1
          fi
          
      # Step 4: Verify the RPM signature (if applicable)
      - name: Verify RPM signature
        run: |
          rpm --checksig devops-gpt-0.0.1.x86_64.rpm
